package com.moviesvc.moviesvc.entity;

import java.util.Objects;
import java.util.UUID;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
@DynamoDBTable(tableName = "movie")
public class Movie {

	private UUID movieId;
	private String name;
	// TODO: should be an enum
	private String genre;
	private String duration;
	private String description;
	private String language;
	private double ratings;


    @DynamoDBHashKey(attributeName = "movieId")
    @DynamoDBAutoGeneratedKey
	public UUID getMovieId() {
		return movieId;
	}

	public void setMovieId(UUID movieId) {
		this.movieId = movieId;
	}

	@DynamoDBAttribute
	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@DynamoDBAttribute
	public String getGenre() {
		return genre;
	}

	public void setGenre(String genre) {
		this.genre = genre;
	}

	@DynamoDBAttribute
	public String getDuration() {
		return duration;
	}

	public void setDuration(String duration) {
		this.duration = duration;
	}

	@DynamoDBAttribute
	public String getDescription() {
		return description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@DynamoDBAttribute
	public String getLanguage() {
		return language;
	}

	public void setLanguage(String language) {
		this.language = language;
	}

	@DynamoDBAttribute
	public double getRatings() {
		return ratings;
	}

	public void setRatings(double ratings) {
		this.ratings = ratings;
	}

	public Movie(UUID movieId, String name, String genre, String duration, String description, String language,
			double ratings) {
		super();
		this.movieId = movieId;
		this.name = name;
		this.genre = genre;
		this.duration = duration;
		this.description = description;
		this.language = language;
		this.ratings = ratings;
	}

	public Movie() {

	}

	@Override
	public String toString() {
		return "Movie [name=" + name + ", genre=" + genre + ", duration=" + duration + ", description=" + description
				+ ", language=" + language + ", ratings=" + ratings + "]";
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		Movie other = (Movie) obj;
		return Objects.equals(language, other.language) && Objects.equals(name, other.name);
	}

}
