package com.moviesvc.moviesvc.entity;

import java.util.UUID;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

@DynamoDBTable(tableName = "screen")
public class Screen {
	private UUID screenID;
	private String name;
	private UUID theatreID;
	private int totalSeats;
	
	public Screen() {}
	
	public Screen(UUID screenID, String name, UUID theatreID, int totalSeats) {
		super();
		this.screenID = screenID;
		this.name = name;
		this.theatreID = theatreID;
		this.totalSeats = totalSeats;
	}
	
	@DynamoDBHashKey
	@DynamoDBAutoGeneratedKey
	public UUID getScreenID() {
		return screenID;
	}
	public void setScreenID(UUID screenID) {
		this.screenID = screenID;
	}
	
	@DynamoDBAttribute
	public String getName() {
		return name;
	}
	public void setName(String name) {
		this.name = name;
	}
	
	@DynamoDBAttribute
	public UUID getTheatreID() {
		return theatreID;
	}
	public void setTheatreID(UUID theatreID) {
		this.theatreID = theatreID;
	}
	
	@DynamoDBAttribute
	public int getTotalSeats() {
		return totalSeats;
	}
	public void setTotalSeats(int totalSeats) {
		this.totalSeats = totalSeats;
	}
	
	

}
