package com.moviesvc.moviesvc.entity;

import java.util.UUID;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
@DynamoDBTable(tableName = "seat")
public class Seat {

	private UUID seatID;
	private int seatNumber;
	private UUID screenID;
	private double price;
	private boolean status;

	@DynamoDBHashKey(attributeName = "seatId")
    @DynamoDBAutoGeneratedKey
	public UUID getSeatID() {
		return seatID;
	}

	public void setSeatID(UUID seatId) {
		this.seatID = seatId;
	}

	@DynamoDBAttribute
	public int getSeatNumber() {
		return seatNumber;
	}

	public void setSeatNumber(int seatNumber) {
		this.seatNumber = seatNumber;
	}

	@DynamoDBAttribute
	public UUID getScreenID() {
		return screenID;
	}

	public void setScreenID(UUID screenId) {
		this.screenID = screenId;
	}

	@DynamoDBAttribute
	public double getPrice() {
		return price;
	}

	public void setPrice(double price) {
		this.price = price;
	}

	@DynamoDBAttribute
	public boolean getStatus() {
		return status;
	}

	public void setStatus(boolean status) {
		this.status = status;
	}

	public Seat(UUID seatId, int seatNumber, UUID screenId, double price, boolean status) {
		super();
		this.seatID = seatId;
		this.seatNumber = seatNumber;
		this.screenID = screenId;
		this.price = price;
		this.status = status;
	}

	public Seat() {
		super();
	}

}
