package com.moviesvc.moviesvc.entity;

import java.util.List;
import java.util.UUID;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

@DynamoDBTable(tableName = "show")
public class Show {

	private UUID showId;
	private String date;
	private UUID movieId;
	private UUID theatreId;
	// TODO : discussion
	private UUID cityId;
	private UUID screenId;
	private String startTime;
	private String endTime;
	private List<Seat> seats;

	@DynamoDBHashKey(attributeName = "showId")
	@DynamoDBAutoGeneratedKey
	public UUID getShowId() {
		return showId;
	}

	public void setShowId(UUID showId) {
		this.showId = showId;
	}

	@DynamoDBAttribute
	public String getDate() {
		return date;
	}

	public void setDate(String date) {
		this.date = date;
	}

	@DynamoDBAttribute
	public UUID getMovieId() {
		return movieId;
	}

	public void setMovieId(UUID movieId) {
		this.movieId = movieId;
	}

	@DynamoDBAttribute
	public UUID getTheatreId() {
		return theatreId;
	}

	public void setTheatreId(UUID theatreId) {
		this.theatreId = theatreId;
	}

	@DynamoDBAttribute
	public UUID getCityId() {
		return cityId;
	}

	public void setCityId(UUID cityId) {
		this.cityId = cityId;
	}
    
	@DynamoDBAttribute
	public UUID getScreenId() {
		return screenId;
	}

	public void setScreenId(UUID screenId) {
		this.screenId = screenId;
	}

	@DynamoDBAttribute
	public String getStartTime() {
		return startTime;
	}

	public void setStartTime(String startTime) {
		this.startTime = startTime;
	}

	@DynamoDBAttribute
	public String getEndTime() {
		return endTime;
	}

	public void setEndTime(String endTime) {
		this.endTime = endTime;
	}

	@DynamoDBAttribute
	public List<Seat> getSeats() {
		return seats;
	}

	public void setSeats(List<Seat> seats) {
		this.seats = seats;
	}

	@Override
	public String toString() {
		return "Show [date=" + date + ", movieId=" + movieId + ", theatreId=" + theatreId + ", cityId=" + cityId
				+ ", startTime=" + startTime + ", endTime=" + endTime + ", seats=" + seats + "]";
	}

	public Show(UUID showId, String date, UUID movieId, UUID theatreId, UUID cityId, UUID screenId, String startTime, String endTime,
			List<Seat> seats) {
		super();
		this.showId = showId;
		this.date = date;
		this.movieId = movieId;
		this.theatreId = theatreId;
		this.cityId = cityId;
		this.screenId=screenId;
		this.startTime = startTime;
		this.endTime = endTime;
		this.seats = seats;
	}

	public Show() {
		super();
	}

}
